### ISSUE TITLE
CSS, CSS lol!!!

### ISSUE THREAD

**Issue by jeffgvegas** [chrisfinBD/rockPaperScissors#1]
Great work with the Javascript

1.Program runs good!!

2.Try removing the // on Line 4 of your css file (NOT VALID CODE), not sure if you were trying to comment out or what ?
		If that is the case you would use /* to open comment and */ to close it

3.Maybe use some css to move your buttons(“Go”, “Play Again?”) outside of your weapon choices. Same with your result.

4.Add some css eye candy.

**Comment by jwoertink** [comment]
@jeffgvegas Good feedback. CSS can be a bit subjective. In these cases, you could take a screenshot of what might be messed up to make it clear "this look broke" or whatever.
